# Generated by Django 4.1.5 on 2023-02-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_career_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Career1',
        ),
    ]
