# Generated by Django 4.1.5 on 2023-03-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career1',
            new_name='Career',
        ),
    ]
