# Generated by Django 4.1.5 on 2023-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_rename_career_jobapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='resume',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
