# Generated by Django 4.1.5 on 2023-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_alter_jobapp_email_alter_jobapp_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=200)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('JobType', models.CharField(max_length=111)),
                ('JobRole', models.CharField(max_length=122)),
                ('Location', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Jobapp',
        ),
    ]
